name: Clara
version: '1.0-SNAPSHOT'
main: com.mael.Clara.Main
api-version: '1.19'
commands:
  config:
  heal:
    description: remplis votre vie
    usage: /heal
  cc:
  console:
  help:
  spawn:
  pls: