name: Clara
version: 'Alpha1.0'
author: fatal97412x
main: com.mael.Clara.Main
api-version: '1.19'
commands:
  config:
  heal:
    description: Restaure la vie du joueur.
    usage: /heal
  hello:
    description:
      usage:
  console:
  help:
    description: Obtenir de l'aide en jeu.
    usage: /help
  spawn:
    description: Retourne le joueur au point de spawn.
    usage: /spawn
  pls:
  t:
  pluginlist:
  profile:
  clara:
  gameselection: